name: Build and deploy Node.js app to Azure Web App - Group8md

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls -la # For Unix-like systems

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and start backend
        run: |
          cd backend
          npm install
          npm start & # Start the backend in the background
          sleep 10 # Give it a moment to start

      - name: Install and start client
        run: |
          cd client
          npm install
          CI=false npm start & # This will allow the start command to proceed without linting errors
          sleep 10

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip # This includes all files in the current directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'group8md'
          package: ./release # Use the release directory
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c87a45dc3ee42a3b7b624bb1b2ea763 }}
